### ISSUE TITLE
Sortable Table?

### ISSUE THREAD

**Issue by quinnj** [johnmyleswhite/Vega.jl#1]
I'm pretty unfamiliar with Vega, but I do know some d3 and actually built a simple wrapper that took a dataframe and produced a basic bar plot and/or table. This was mainly for data exploration and was quite handy but I failed to keep it updated. I was recently thinking of going back to revisit, but remembered hearing about Vega, so I decided to give it a go.

Now to the issue, I'm actually wondering how hard/possible it would be to add a simple table output as an output option. This is handy as it's not always easy/convenient to explore the contents of a DataFrame or large array and you can add some simple capabilities like column sorting that make it really quick to see data values. (I based my version off of a capability in RStudio to `view` a data.frame. It opens up a new tab in the editor to display up to 1000 rows of a data.frame.)

Anyway, consider this a feature request, and hopefully in the next few weeks I can find some more time to explore Vega and maybe implement this myself.

Cheers.

**Comment by randyzwitch** [comment]
Closing this zombie issue, as it's not really a core Vega functionality/seems better served somewhere else in the DataFrames universe.
