### ISSUE TITLE
Waterfall chart sorts categories alphabetically

### ISSUE THREAD

**Issue by beingalink** [johnmyleswhite/Vega.jl#100]
The [example waterfall chart](http://johnmyleswhite.github.io/Vega.jl/waterfall.html) gets its categorial x-axis sorted alphabetically which, of course, doesn't make any sense. The rendered chart on that page looks correct but if you re-run the example code the categories get sorted.

**Comment by randyzwitch** [comment]
Thanks, I think this broke it. https://github.com/johnmyleswhite/Vega.jl/issues/97 Should be a quick fix.

**Comment by randyzwitch** [comment]
Will bump the tag shortly, if you're in a hurry you can do `Pkg.checkout("Vega")`

**Comment by beingalink** [comment]
Wow, that was quick! Thanks a lot and keep up the great work.
