### ISSUE TITLE
layer() fails to group more then 2 plots

### ISSUE THREAD

**Issue by axsk** [johnmyleswhite/Vega.jl#106]
``` julia
using Vega
layer(layer(scatterplot(x=[1],y=[1]), scatterplot(x=[2],y=[2])), scatterplot(x=[3],y=[3]))
```
returns a not rendering vega plot :(

**Comment by randyzwitch** [comment]
To be quite honest, it barely works for two plots! That's why I've left it undocumented (though I probably shouldn't have exported it)

The only question is whether someone can fix it before I have time to, which is probably several months away
