### ISSUE TITLE
Line plot doesn't support dates in x-axis

### ISSUE THREAD

**Issue by shivaramkrs** [johnmyleswhite/Vega.jl#107]
I am trying to use dates in x-axis, this gives blank plot in lineplot. I get a graph if I use numbers x=1:N.

**Comment by randyzwitch** [comment]
Please post a reproducible code sample.

**Comment by randyzwitch** [comment]
This appears that it's a known issue with JSON.jl, it's not a Vega.jl problem per se.

https://github.com/JuliaLang/JSON.jl/issues/90

The short-term fix is to convert your Julia `Date` types to `String` dates.

**Comment by shivaramkrs** [comment]
It seems JSON.jl issue. Thank you.

**Comment by randyzwitch** [comment]
Closing this, presuming my patch will get accepted as the fix
