### ISSUE TITLE
Need copy image option in the HTML file

### ISSUE THREAD

**Issue by shivaramkrs** [johnmyleswhite/Vega.jl#108]
When we right click on the image in the browser, only option we get is save image as. It will be useful if we can have copy image option as well.

**Comment by randyzwitch** [comment]
When I right-click using Chrome on OSX, I get 'Copy Image'. What browser are you using?

**Comment by shivaramkrs** [comment]
I am using Chrome on Windows 7 machine.

**Comment by randyzwitch** [comment]
This suggests that it's a Chrome-level issue; I don't want to create any additional library dependencies or sniffing for the browser type from the user-agent just to fix this.

http://stackoverflow.com/questions/12255444/copy-svg-images-from-browser-to-clipboard
