### ISSUE TITLE
Plotting issues under Firefox?

### ISSUE THREAD

**Issue by tlnagy** [johnmyleswhite/Vega.jl#123]
Same page in Chrome 49 and Firefox 45 on OS X 10.11

Firefox (safe mode, no plugins):
<img width="1101" alt="screen shot 2016-04-12 at 15 15 14" src="https://cloud.githubusercontent.com/assets/1661487/14477257/7f9daffc-00c1-11e6-91a3-e49c99ab3a23.png">

Chrome:
<img width="954" alt="screen shot 2016-04-12 at 15 16 39" src="https://cloud.githubusercontent.com/assets/1661487/14477268/955bcac2-00c1-11e6-860c-69bc66ebda15.png">

**Comment by randyzwitch** [comment]
I just downloaded Firefox 45.0.2 for OSX, works fine straight from install. Not sure what to say.

<img width="1440" alt="screen shot 2016-04-13 at 9 45 41 am" src="https://cloud.githubusercontent.com/assets/2762787/14495300/d8ea78e2-015c-11e6-9ed3-c2b2b872c16d.png">
