### ISSUE TITLE
visualization of image/bitmap?

### ISSUE THREAD

**Issue by jingpengwu** [johnmyleswhite/Vega.jl#132]
This looks a very nice visualization tool.
any support of image/bitmap? 
show gray/RGB images?
show julia array?

**Comment by randyzwitch** [comment]
Could you be more specific in what you are looking for? Links to examples on the web are fine, or just more than 3 words per visualization type to explain would be helpful

**Comment by jingpengwu** [comment]
Actually, they are all one function:
`just show a image on the web`
here is an example:
http://r.ddmcdn.com/s_f/o_1/cx_633/cy_0/cw_1725/ch_1725/w_720/APL/uploads/2014/11/too-cute-doggone-it-video-playlist.jpg

**Comment by randyzwitch** [comment]
I'm sorry, I'm not trying to be difficult...do you literally just want to display a picture? You don't want to manipulate it, it isn't read into Julia or the result of a Julia operation? You just want do `show_dog()` and have the following get displayed?

 ![](http://r.ddmcdn.com/s_f/o_1/cx_633/cy_0/cw_1725/ch_1725/w_720/APL/uploads/2014/11/too-cute-doggone-it-video-playlist.jpg)

**Comment by JobJob** [comment]
Umm... possibly off-topic but +1 for `show_dog()`

**Comment by jingpengwu** [comment]
Actually, I would like to use vega with Escher.jl. Being able to manipulate the picture would be a big plus. It is a little bit too demanding for a package based on D3 and JSON. I'll close this issue.

**Comment by randyzwitch** [comment]
Thanks @jingpengwu. So you can display pictures in Escher without having to use Vega at all. If you're looking to do image processing (for lack of a better word, "Photoshopping") using Vega, then yes this isn't the package.
