### ISSUE TITLE
how to multiple plots?

### ISSUE THREAD

**Issue by jmarcellopereira** [johnmyleswhite/Vega.jl#140]
how to multiple plots?
using Vega

x = 1:100
y = sin(x).*x
g = x.^2
lineplot(x = x,y = y and ?????)

**Comment by randyzwitch** [comment]
Currently, layering of plots doesn't work. To have multiple series, you can use the group parameter of many visualizations:

http://johnmyleswhite.github.io/Vega.jl/lineplot.html

**Comment by randyzwitch** [comment]
Related #142

**Comment by randyzwitch** [comment]
#142 makes progress towards layering. Will open a meta issue for outstanding layer topics.
