### ISSUE TITLE
Vega.jl not run in Julia 0.6

### ISSUE THREAD

**Issue by 4lrdyD** [johnmyleswhite/Vega.jl#151]
julia> Pkg.test("Vega")
INFO: Computing test dependencies for Vega...
INFO: Installing DataArrays v0.6.2
INFO: Installing DataFrames v0.10.0
INFO: Installing FileIO v0.5.1
INFO: Installing GZip v0.3.0
INFO: Installing RData v0.1.0
INFO: Installing RDatasets v0.2.0
INFO: Installing SortingAlgorithms v0.1.1
INFO: Testing Vega

WARNING: deprecated syntax "abstract AbstractVegaType" at C:\Users\user\.julia\v0.6\Vega\src\primitives/definetypes.jl:2.
Use "abstract type AbstractVegaType end" instead.
ERROR: LoadError: LoadError: UndefVarError: call not defined
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:569
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:569
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\user\.julia\v0.6\Vega\src\primitives/definetypes.jl, in expression starting on line 3
while loading C:\Users\user\.julia\v0.6\Vega\src\Vega.jl, in expression starting on line 30
ERROR: LoadError: Failed to precompile Vega to C:\Users\user\.julia\lib\v0.6\Vega.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:703
 [2] _require(::Symbol) at .\loading.jl:490
 [3] require(::Symbol) at .\loading.jl:398
 [4] include_from_node1(::String) at .\loading.jl:569
 [5] include(::String) at .\sysimg.jl:14
 [6] process_options(::Base.JLOptions) at .\client.jl:305
 [7] _start() at .\client.jl:371
while loading C:\Users\user\.julia\v0.6\Vega\test\runtests.jl, in expression starting on line 3
================================[ ERROR: Vega ]=================================

failed process: Process(`'C:\Users\user\AppData\Local\Julia-0.6.0\bin\julia.exe' -Cx86-64 '-JC:\Users\user\AppData\Local\Julia-0.6.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\user\.julia\v0.6\Vega\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: Removing DataArrays v0.6.2
INFO: Removing DataFrames v0.10.0
INFO: Removing FileIO v0.5.1
INFO: Removing GZip v0.3.0
INFO: Removing RData v0.1.0
INFO: Removing RDatasets v0.2.0
INFO: Removing SortingAlgorithms v0.1.1
ERROR: Vega had test errors

**Comment by randyzwitch** [comment]
Yes, this is known from #130 as well as on the README. If this is something you are interested in fixing, I'd happily accept a pull request

**Comment by 4lrdyD** [comment]
Hello, i don't know how i'd be process and what do i do

**Comment by randyzwitch** [comment]
The process is to make a fork of this repository into your own account, fix all the issues that Julia complains about until it runs again. However, if you're not familiar with this process, this might not be the best issue to start with, as the code Julia is complaining about is a bit low-level and hard to understand

**Comment by randyzwitch** [comment]
I pushed the necessary fixes to master, will tag a new version for METADATA when the testing scripts pass

**Comment by 4lrdyD** [comment]
you're right, i'm unfamiliar with the process and I'm just starting to learn, I needed to work with graphics and I want to use Vega.jl, however i'll try to learn more about it, thanks a lot
