### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by davidanthoff** [johnmyleswhite/Vega.jl#153]
The current ``master`` seems to work on julia 0.6, but the current tagged version doesn't. @randyzwitch could you tag a version? Thanks!

**Comment by randyzwitch** [comment]
Are you actually using this package? At some point, I was planning on re-writing it to use Vega 3, but it hasn't been my highest priority.

**Comment by davidanthoff** [comment]
Yeah, for simple plots it works really well and I sometimes use it for that :)

For the Vega 3 story, have you looked at @fredo-dedup auto-code generation in https://github.com/fredo-dedup/VegaLite.jl? It essentially takes the JSON schema for vega-lite and then generates the julia wrappers automatically. It is really nifty... I am of two minds about it from an API UI point of view, though, I feel the API one ends up with is just not super julian... I've also started a package https://github.com/davidanthoff/VegaCore.jl that could have shared display and file IO stuff for both Vega.jl and VegaLite.jl. The idea for that would be that the package just provides support for dealing with JSON strings that are vega/vega-lite specs and then handles things like saving in various formats, getting data into it etc. The whole thing is a bit vague at this point, but somehow it strikes me that Vega.jl and VegaLite.jl could share a fair bit of code.

**Comment by randyzwitch** [comment]
Submitted the new tag to METADATA just now, so hopefully it gets merged quickly. I can almost guarantee something is broken with this 0.6 support ;)

That's awesome though that you use this at all. I've meant to come back, but so few users seem to exist that it hasn't been a priority. I haven't looked at VegaLite.jl source...the problem for me was never really the types, but rather defining an easy API and easy abstractions from the low-level Vega spec.

As far as your VegaCore.jl, that sounds like a great idea, but at the same time, with Vega 3 being able to go back and forth between Vega full and Vega-Lite within the browser, it might make more sense to try and just do a Vega repo. But, I also recognize that people may not be interested in my Vega API syntax, so there's obviously room for other Vega packages.

**Comment by davidanthoff** [comment]
My gut feeling is that creating a really good julian API is really quite tricky and will require a fair bit of work. Probably with some false starts, lots of iterations etc. I've thought about this (more in the context of vega-lite) for about half a year now, and I'm still conflicted what a nice API would look like...

That was the main reason I thought a VegaCore.jl package might be useful: I think that could be quite stable pretty quickly and useful. What I have in mind in terms of API for that is essentially the following (I'm writing this up in terms of vegalite, but the same should also work for vega):
````julia

# Option 1 to create a spec, use a string macro and write the JSON directly:
spec = vl"""
{
  "data": {"url": "data/seattle-weather.csv"},
  "mark": "bar",
  "encoding": {
    "x": {
      "timeUnit": "month",
      "field": "date",
      "type": "ordinal"
    },
    "y": {
      "aggregate": "mean",
      "field": "precipitation",
      "type": "quantitative"
    }
  }
}
"""

# Option 2 to get a spec object, load it from a file (with FileIO.jl integration):
spec = load("myspec.vegalite")

# Option 3 to get a spec object would be DataVoyager.jl, details to be hashed out
spec = Voyager(df) # Or something like that
# and actually something based on lyra might be possible for vega. I checked with the lyra folks
# and they plan to revive that project this summer

# Hook into the whole multimedia interface, so that
display(spec)
# just works. That should give us IJulia, VS Code and
# BlinkDisplay.jl (once it is done) integration. Not sure about the Juno
# story these days, but maybe that would also be enough

# Also hook into the FileIO save story, so that
save("file.pdf", spec)
save("file.png", spec)
save("file.eps", spec)
save("file.svg", spec)
save("file.vegalite", spec)
# all work. 

# Finally integrate with IterableTables.jl, so that we can pipe tables into a spec
df |> spec
# or
spec(df)
# or
load!(spec, df)
# or something like that. For vega this would need to be a bit more sophisticated because
# it supports multiple data sources per spec, right? Not sure about vega-lite, actually...
````
Most of that works in VegaCore.jl right now for vega-lite, and I think could be quite useful by itself. Plus it could be quite a stable package.

I then feel that VegaLite.jl could try to come up with a high-level julia API to create vega-lite specs (but that would be all it does, it wouldn't try to handle all the things that are already in VegaCore.jl), and Vega.jl could do the same for vega. Those packages could be quite a bit less stable, I guess, or rather it would take potentially some time to get their design right.

Oh, one more random thought: maybe it would also make sense to move the predefined visualizations from Vega.jl into another package? That seems a completely different API, that is actually quite straightforward, i.e. potentially quite stable, and pretty much doesn't need any change? I haven't looked at the details of that, might be a silly idea, just a thought.

**Comment by randyzwitch** [comment]
For my usage, there's no benefit to moving the pre-defined visualizations from the Vega.jl library. I took over maintaining this package because I needed to generate Vega specifications quickly at work. So I wrote the common visualizations I was looking for, with the ability through the types to set whatever properties I wanted. Ultimately, I'd send a working prototype as JSON/HTML to an internal UI person who would integrate it into an internal tool (usually dashboards)

Unlike everyone else, I'm not on board with the Plots/Makie "one interface to rule them all" idea. My ideal API is one that is self-evident without reading the documentation, for simplish ideas. I'm getting closer with ECharts.jl, which can almost be a v2 of what Vega.jl would've become

http://randyzwitch.com/ECharts.jl/

**Comment by davidanthoff** [comment]
ECharts.jl looks nice! I'm completely with you on the "one interface to rule them all" idea, I'm not sold on that.

I think my main goal is to have something that can compete with ggplot2. So it doesn't have to be as simple as what you are creating with ECharts.jl. But I also don't have a good plan of how I want that to look, so I think this just requires more thinking :)

The one thing that I do feel would be useful to share across Vega.jl and VegaLite.jl is stuff like exporting specs into various file formats, the display systems etc. For VegaLite.jl (and now VegaCore.jl) I'm essentially installing a private NodeJS version, and then I can run the vega/vega-lite compiler on a spec file to create a svg file, and then I use Cairo.jl and friends to save things as pdf, png etc.

None of this is high priority, I'll keep you in the loop if I have any new ideas or make any progress with any of this.

**Comment by randyzwitch** [comment]
Absolutely, I’d definitely love to collaborate. At one time, there was a crude sketch of Vega ggplot, so it’s definitely possible

**Comment by randyzwitch** [comment]
Tagging at METADATA failed, one because a test failed but also because RDatasets doesn't support DataFrames yet. What a mess.

**Comment by randyzwitch** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/12701
