### ISSUE TITLE
What wrong ?  tojson(vg) ERROR: UndefVarError: tojson not defined

### ISSUE THREAD

**Issue by programistawpf** [johnmyleswhite/Vega.jl#154]
What wrong ? 
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using Vega
INFO: Precompiling module Vega.

julia> vg = VegaVisualization()
Vega.VegaVisualization
  name: String "Vega Visualization"
  width: Int64 450
  height: Int64 450
  padding: String "auto"
  viewport: Void nothing
  background: Void nothing
  data: Void nothing
  scales: Void nothing
  axes: Void nothing
  marks: Void nothing
  legends: Void nothing
  signals: Void nothing
  predicates: Void nothing
  modify: Void nothing

julia> tojson(vg)
ERROR: UndefVarError: tojson not defined

Paul

**Comment by randyzwitch** [comment]
Use `print(vg)` to print the JSON representation of your chart. Just a warning, this is still using Vega 2, not the updated Vega 3 library.
