### ISSUE TITLE
Is Vega.jl discontinued? I can't make a waterfall graph

### ISSUE THREAD

**Issue by santiagopradoloy** [johnmyleswhite/Vega.jl#158]
I tried the sample code in https://johnmyleswhite.github.io/Vega.jl/waterfall.html and I get`UndefVarError: waterfall not defined

Stacktrace:
 [1] top-level scope
   @ :0
 [2] eval
   @ .\boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1116`

**Comment by johnmyleswhite** [comment]
The README seems pretty unclear anyone will work on this again:

```
NOTE: THIS PACKAGE IS IN A STATE OF LIMBO
```

That's from 2018.

**Comment by santiagopradoloy** [comment]
Makes sense. 

I did figure it out with VegaLite.jl though

**Comment by davidanthoff** [comment]
Note that there is also https://github.com/queryverse/Vega.jl, which is actually registered in General. It uses the same approach as VegaLite.jl, just for Vega. The two packages also work together well.
