### ISSUE TITLE
Parameterize modifiers.jl functions as much as possible

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#35]
Rather than having the values hard-coded in, we should have things like `font`, `fill`, `size` be parameters on the `title!` function.

```julia
@compat function title!(v::VegaVisualization, title::String)
	titlemark = VegaMark(_type = "text", from = VegaMarkFrom(value = title))
    enterprops = VegaMarkPropertySet(x = VegaValueRef(value = v.width / 2),
                                     y = VegaValueRef(value = -50),
                                     text = VegaValueRef(value = title),
                                     fill = VegaValueRef(value = "black"),
                                     fontSize = VegaValueRef(value = 12))
	titlemark.properties = VegaMarkProperties(enter = enterprops)
	push!(v.marks, titlemark)
	return v
end
```

Fix these in no particular order (but probably `title!` first since it already has hard-coded values)
- [x]  `xlab!`
- [x]  `ylab!`
- [x]  `xlim!`
- [x]  `ylim!`
- [x]  `title!`
- [x]  `legend!`

**Comment by randyzwitch** [comment]
Fix these in no particular order (but probably `title!` first since it already has hard-coded values)
- [ ]  `xlab!`
- [ ]  `ylab!`
- [ ]  `xlim!`
- [ ]  `ylim!`
- [ ]  `title!`
- [ ]  `legend!`

**Comment by josep2** [comment]
Just getting around to this. Issue #9 doesn't close this issue, is that right?

**Comment by randyzwitch** [comment]
Cool, glad you're still interested in contributing.

This is the relevant meta issue; the six functions above are ripe for customization, adding optional arguments for font, font size, font color, etc.

**Comment by randyzwitch** [comment]
Functions are converted over to be `v::VegaVisualization` as the only required argument, all other parameters will be keywords.

Will likely continue to work on this today, as I'm building graphs and fixing bugs all at once.
