### ISSUE TITLE
Error showing value of type VegaVisualization

### ISSUE THREAD

**Issue by EricForgy** [johnmyleswhite/Vega.jl#37]
Hi,

I just tried installing Vega.jl and running one of the samples from the REPL and get the following error:

---------

    julia> using Vega, KernelDensity, Distributions
    
    julia> x = rand(Beta(3.0, 2.0), 1_000_000)
    1000000-element Array{Float64,1}:
     0.681125
     0.146343
     0.405623
     0.662026
     0.294268
     0.801663
     0.636717
     0.414619
     0.636137
     0.091407
     ⋮
     0.704455
     0.152232
     0.618623
     0.354213
     0.979615
     0.521798
     0.424103
     0.89213
     0.366749
     0.578046
    
    julia> k = kde(x)
    UnivariateKDE{FloatRange{Float64}}    (-0.038363825324927374:0.0005292997232250555:1.0445834083935361,[1.0391e-6,8.69388e-7,7.35752e-7,6.3297e-7,5.5686e-7,5.04152e-7,4.72372e-7,4.59763e-7,4.65203e-7,4.88159e-7  …  7.03447e-6,5.82931e-6,4.82242e-6,3.98322e-6,3.28559e-6,2.7073e-6,2.22948e-6,1.83615e-6,1.51386e-6,1.25132e-6])
    
    julia> areaplot(x = k.x, y = k.density)
    Error showing value of type VegaVisualization:
    ERROR: could not spawn `start    'C:\Users\ERICFO~1\AppData\Local\Temp\jul6AFA.tmp.vega.html'`: no such file or directory (ENOENT)
     in _jl_spawn at process.jl:217 (repeats 2 times)

-----------------------

Here is my

    julia> versioninfo()
    Julia Version 0.3.11
    Commit 483dbf5* (2015-07-27 06:18 UTC)
    Platform Info:
      System: Windows (x86_64-w64-mingw32)
      CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

I'm still a newbie. Any ideas? Is it supposed to work from the REPL?

Edit: I can confirm there is no such jul41A.tmp.vega.html file in that location, so however it was supposed to be generated, it didn't get generated.

**Comment by EricForgy** [comment]
Sorry. I was so excited to try it out, I didn't see this:

Vega.jl is only targeted to work against v0.4 of Julia (or newer). However, some use of the Compat.jl package to provide backwards compatibility has been done. If you are looking for increased backwards capatibility, please submit a pull request as necessary to support your preferred version of Julia.

**Comment by EricForgy** [comment]
Oops. Sorry again. I get the same issue with

    julia> versioninfo()
    Julia Version 0.5.0-dev+9
    Commit 248eb0b (2015-09-10 04:03 UTC)
    Platform Info:
      System: Windows (x86_64-w64-mingw32)
      CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

**Comment by randyzwitch** [comment]
Hey Eric - 

Yes, the hope is that it would work with Windows and at the REPL, but unfortunately I don't have a Windows machine to test that. You're the first person to try I suppose.

Since the temp HTML files don't seem to be getting created, it sounds like there's at least one, maybe two problems. It's either:

https://github.com/johnmyleswhite/Vega.jl/blob/master/src/render.jl#L4

or

https://github.com/johnmyleswhite/Vega.jl/blob/master/src/render.jl#L99

I'll try and get access to a Windows machine to figure out what isn't working. Sorry about that!

**Comment by randyzwitch** [comment]
Ok, can you do `Pkg.checkout("Vega")` to get the latest master branch, then try again? I just downloaded a Windows VM and my fix triggers IE with the barplot example.

If you get an "ActiveX blocked this content" or similar, just hit enable content.

**Comment by EricForgy** [comment]
Hi Randy. Thanks for quick fix.

I am still having some trouble, but it seems to a bigger issue than just Vega.jl.

    julia> Pkg.checkout("Vega")
    INFO: Checking out Vega master...
    INFO: Pulling Vega latest master...
          0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
    AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x210000, State 0x10000
    C:\Program Files\Julia-0.5.0-dev\Git\bin\sh.exe: *** Couldn't reserve space for cygwin's heap,     Win32 error 0
    ERROR: failed process: Process(`git '--work-tree=C:\Users\Eric Forgy\.julia\v0.5\Vega' '--git-    dir=C:\Users\Eric Forgy\.julia\v0.5\Vega\.git' pull -q --ff-only`, ProcessExited(1)) [1]
     in pipeline_error at process.jl:548

I get this error now even if I just:

    julia> Pkg.update()
    INFO: Updating METADATA...
          0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
    AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x210000, State 0x10000
    C:\Program Files\Julia-0.5.0-dev\Git\bin\sh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
    ERROR: failed process: Process(`git pull --rebase -q`, ProcessExited(1)) [1]
     in pipeline_error at process.jl:548

Will keep you posted...

Thanks!

**Comment by EricForgy** [comment]
A little time and a reboot for good measure did the trick. It seems to be working now. Thanks!

**Comment by randyzwitch** [comment]
Glad you got it sorted out. After you've played with it for a while, if there any features you think are critical, please open an issue, as I'd love to make this into a viable package!
