### ISSUE TITLE
After installing Julia v0.4 I got the following ERROR: x, y and group must all have the same length

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#38]
Hi,

I just updated my julia installation to the stable v0.4 (Version 0.4.0-rc1+7 (2015-09-10 20:01 UTC)). After that I removed my former installation of Vega and installed it again by calling a Pkg.add("Vega")

After that, I am no longer able to run a simple example from the webpage. The plotting of a wordcloud. Below you can find the code I am running and the error message I got:

using Vega

corpus = [
       "Julia is a high-level, high-performance dynamic programming language for technical computing, with syntax that is familiar to users of other technical computing environments. It provides a sophisticated compiler, distributed parallel execution, numerical accuracy, and an extensive mathematical function library. Julia’s Base library, largely written in Julia itself, also integrates mature, best-of-breed open source C and Fortran libraries for linear algebra, random number generation, signal processing, and string processing. In addition, the Julia developer community is contributing a number of external packages through Julia’s built-in package manager at a rapid pace. IJulia, a collaboration between the IPython and Julia communities, provides a powerful browser-based graphical notebook interface to Julia.",
       "Julia programs are organized around multiple dispatch; by defining functions and overloading them for different combinations of argument types, which can also be user-defined. For a more in-depth discussion of the rationale and advantages of Julia over other systems, see the following highlights or read the introduction in the online manual."
       ]

julia> wc = wordcloud(x = corpus)
ERROR: x, y and group must all have the same length
 in add_data! at /home/cdesantana/.julia/v0.4/Vega/src/intermediates/data.jl:9
 in wordcloud at /home/cdesantana/.julia/v0.4/Vega/src/derived/wordcloud.jl:4

Any suggestion will be much appreciated!

Thanks!

**Comment by randyzwitch** [comment]
Sorry about that, the documentation is ahead of the METADATA version. I'll bump up the version number.

In the meantime, if you do `Pkg.checkout("Vega")`, it should hopefully work for you.

I'd love to get your feedback after using the package...if there are any critical features that are holding you back, please create an issue.

**Comment by cndesantana** [comment]
Great! Thanks for your response and please don't be sorry! The package is amazing and you guys are doing a great job!!

It worked for my the suggestion of calling a "Pkg.checkout("Vega")" before calling the package. Just did:

julia> Pkg.checkout("Vega")
INFO: Checking out Vega master...
INFO: Pulling Vega latest master...
INFO: No packages to install, update or remove

julia> using Vega
INFO: Recompiling stale cache file /home/cdesantana/.julia/lib/v0.4/Vega.ji for module Vega.

julia> corpus = [
       "Julia is a high-level, bla bla bla....",
       "Julia programs are organized ble ble ble..."
       ];

                                                                                                                                                             julia> wc = wordcloud(x = corpus)


and everything worked perfectly!

Thanks!

**Comment by uozden** [comment]
Dear @randyzwitch, I have installed Vega and typed in the code below. It gives the following error. I am using Julia 0.4 on Windows 10 -32bit. Thank you for your help. 
````````
using Vega

fruit = ["peaches", "plums", "blueberries", "strawberries", "bananas"]
bushels = [100, 32, 180, 46, 21]

piechart(x = fruit, y = bushels)

```````
LoadError: TypeError: typeassert: expected Union{AbstractString,Array{T,N},Tuple{AbstractString,Int64}}, got Tuple{ASCIIString,Int32}
while loading In[6], in expression starting on line 6

 in piechart at C:\........\.julia\v0.4\Vega\src\derived/piechart.jl:31

``````
