### ISSUE TITLE
"Cairo must be installed to use the PNG backend" error after trying to run Vega.jl + Cairo.jl + Gadfly.jl

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#39]
I just installed the new stable version of Julia (Version 0.4.0-rc1+7 (2015-09-10 20:01 UTC))

And I am trying to run Gadfly together with Vega to generate a figure of a word-cloud. I am using simple examples extracted from http://johnmyleswhite.github.io/Vega.jl/wordcloud.html and http://gadflyjl.org/

I am using Vega.jl to create the word-cloud:

        julia> Pkg.checkout("Vega")
        INFO: Checking out Vega master...
        INFO: Pulling Vega latest master...
        INFO: No packages to install, update or remove

        julia> using Vega

        julia> corpus = [
               "Julia is a high-level, bla bla bla....",
               "Julia programs are organized ble ble ble..."
               ];

        julia> wc = wordcloud(x = corpus);

And I am trying to use Cairo.jl + Gadfly.jl to plot the word-cloud into a PNG figure. I am doing the following:

        julia> Pkg.checkout("Cairo")
        INFO: Checking out Cairo master...
        INFO: Pulling Cairo latest master...
        INFO: No packages to install, update or remove

        julia> Pkg.checkout("Gadfly")
        INFO: Checking out Gadfly master...
        INFO: Pulling Gadfly latest master...
        INFO: No packages to install, update or remove

        julia> using Gadfly

        julia> draw(PNG("myplot.png", 4inch, 3inch), wc)
        ERROR: Cairo must be installed to use the PNG backend.
         in PNG at /home/cdesantana/.julia/v0.4/Compose/src/Compose.jl:137

Any idea about it? Is it a problem with my installation of Cairo or Gadfly? Is it a compatibility problem between Gadfly and Vega? 

Thanks for any tip!

P.S.: I submitted the same issue in Gadfly github: https://github.com/dcjones/Gadfly.jl/issues/686

**Comment by randyzwitch** [comment]
This is most certainly an issue with something other than Vega. The only thing required for Vega are the JavaScript libraries, there is no PNG exporting (though, it might be possible to do in the future natively in this package).

Given that `wc` is of type `VegaVisualization` when it goes into `draw`, there might be a method needed to be defined with Gadfly. While I've got nothing against Gadfly, I haven't given any thought on how to integrate with it either :)

**Comment by tbreloff** [comment]
If you come up with a way to save PNGs, please let me know.  I'm planning
to add Vega.jl as a backend in Plots.jl, and it will be important for me to
be able to save PNGs for the examples markdown page.  Hacks are accepted,
but I would prefer that it didn't require Gadfly or lots of other
dependencies.

**Comment by cndesantana** [comment]
Thanks for your responses. 

I agree with @tbreloff, it would be great to be able to save things we do with Vega.jl into a figure, doesn't matter the format, actually (PNG, PDF, EPS, TIFF, ...). In my case, I would like to include a wordcloud in a latex manuscript, so EPS, PDF or PNG would be my preferences. 

I will let you know If I find a way by myself.

**Comment by randyzwitch** [comment]
Can one of you throw that up as an issue?

**Comment by cndesantana** [comment]
Done: https://github.com/johnmyleswhite/Vega.jl/issues/40

**Comment by randyzwitch** [comment]
Closing, if you figure it out your approach is almost certainly a hack using Gadfly (and I mean that in the best way possible)
