### ISSUE TITLE
Control chart

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#41]
Not sure if this moves into realm of separate package, but having a quality control chart might be interesting (calculations are pretty easy).

**Comment by randyzwitch** [comment]
Something more elegant looking than the qcc package in R
![screen shot 2015-09-15 at 3 22 59 pm](https://cloud.githubusercontent.com/assets/2762787/9887438/b126bf90-5bbd-11e5-8258-5061b3e4f61d.png)

**Comment by randyzwitch** [comment]
@johnmyleswhite What do you think about this? I mean, I could try and build a whole new package around quality control (of which I'm not an expert), then provide a `QC` composite type for plotting, or I could keep all the logic inside the Vega package for just this one plot (thereby removing having to make a whole QC package).

**Comment by johnmyleswhite** [comment]
If you feel up to it, do it. I'm always anti-feature since I don't have time to do maintenance, but do what you think is worth it and fun enough to enjoy doing.

**Comment by randyzwitch** [comment]
Upon further thought, I'm not going to do this (or, not for a long time). I have no particular expertise here, so I don't want anyone relying on my calculations or having to support it like you say.
