### ISSUE TITLE
Should xlim!, ylim!, xlab!, ylab! all be separate functions?

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#46]
(Time to start being a bit more serious about keeping backwards compatibility/deprecations)

Should the functions just be `yaxis!` and `xaxis!`. If the point is to be declarative or think about chart parts as large chunks, having the axis limits separately from the points might be too granular.

Of course, `Axes` are different from `Scales` in Vega, which argues for keeping separate.

**Comment by spencerlyon2** [comment]
I vote for keeping separate functions

**Comment by randyzwitch** [comment]
That certainly is the easier way to go .

Maybe a rename to `xaxis!`, `yaxis!`, `xscale!` and `yscale!`? I'm about to push some more keyword arguments for #35, and now having a `reverse` and `round` argument doesn't make sense when the function `xlim!/ylim`
