### ISSUE TITLE
Factor out jstypes code

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#50]
Metaprogramming too obscure; it works currently, but if it doesn't work, may not be able to support/fix issues.

Code does 3 things AFAIK:

- [ ] Creates types
- [ ] ~~Creates functions with keyword arguments, so that it's easy to change specific fields in a type without having to specify non-modified fields~~
- [ ] Creates JSON representations from arbitrary composite types

It seems that the types should change infrequently enough such that building them dynamically doesn't save much code. ~~The keyword arguments might be able to be handled using `Base.call` that's already in file?~~ JSON from arbitrary composite types feels like something for the JSON.jl package to handle.

This is a longer-term idea, but I welcome anyone willing to tackle this.

**Comment by spencerlyon2** [comment]
So I don't think point 2 is correct anymore.

When I made my speedup changes I removed the metaprogramming that created a new keyword argument function for every type and replaced it with a 0 argument function that sticks in all the default values from the spec. 

Then all the keyword argument functionality comes through the single function:

```julia
function Base.call{T<:AbstractVegaType}(::Type{T}; kwargs...)
    out = T()
    for (sym, val) in kwargs
        setfield!(out, sym, val)
    end
    out
end
```

We might be able to get away with just that + a single macro that takes a spec and produces the type definition and 0 arg function.

I agree that serializing to json would ideally happen in JSON.jl

**Comment by randyzwitch** [comment]
Even better, told you I didn't really understand the code!

**Comment by randyzwitch** [comment]
It appears that `makecopy` and the related code can just be removed without replacement. I have a Jupyter Notebook with dozens of examples of code and they all still run as expected with the code commented out.

**Comment by randyzwitch** [comment]
Removing `makedefaultfunc` is dependent on allowing defaults to be set becoming part of Base at some point:

https://github.com/JuliaLang/julia/issues/10146

With the ability to set defaults on type construction, then `fielddef` and `maketype` can be removed, leaving only the JSON-generating macros left. 

Of course, could also use https://github.com/mauro3/Parameters.jl in the meantime to get rid of `makedefaultfunction` (and thus add a package dependency and still have another macro), or a number of different solutions, but this issue isn't pressing enough to worry about now.

**Comment by spencerlyon2** [comment]
Would it be easier to work with this code if the expressions were created using `quote` instead of being hand coded?

**Comment by randyzwitch** [comment]
It's not a matter of ease, just that it's the only "magic" part of the code. So from a maintenance perspective, that's undesirable.

It's likely the case that this code never needs to be updated again, but it still feels like a code smell, which is why I'd prefer to get rid of it eventually (I mean, I plain copied it out of another @johnmyleswhite unregistered package)

**Comment by spencerlyon2** [comment]
So JSON.jl will create a json representation of arbitrary composite types:

```
julia> type Foobar
       x::Int64
       y::Float64
       z::AbstractString
       end

julia> ff = Foobar(1, 2, "foo")
Foobar(1,2.0,"foo")

julia> print(json(ff))
{"x":1,"y":2.0,"z":"foo"}
julia> print(json(ff, 2))
{
  "x": 1,
  "y": 2.0,
  "z": "foo"
}
```

The only trick is if you can leverage this and do the `_type` -> `type` transformation that currently needs to happen right now

**Comment by randyzwitch** [comment]
Cool, thanks for finding that. Is that new functionality or has that been there for a while?

Re-writing the single _type key shouldn't be a big deal, compared to all the macro code being excised.

**Comment by randyzwitch** [comment]
Closing, this seems so far down the list of things to worry about relative to adding features. Works fine as-is, leaving it be.
