### ISSUE TITLE
How do I use choropleth with just states

### ISSUE THREAD

**Issue by shashi** [johnmyleswhite/Vega.jl#68]
I googled FIPS and found this list: https://www.mcc.co.mercer.pa.us/dps/state_fips_code_listing.htm

My DataFrame looks like this
```julia
44x2 DataFrames.DataFrame
| Row | s  | x1 |
|-----|----|----|
| 1   | 1  | 2  |
| 2   | 2  | 2  |
| 3   | 4  | 7  |
| 4   | 5  | 2  |
| 5   | 6  | 48 |
| 6   | 8  | 4  |
| 7   | 9  | 4  |
⋮
| 37  | 47 | 9  |
| 38  | 48 | 21 |
| 39  | 49 | 3  |
| 40  | 51 | 7  |
| 41  | 53 | 6  |
| 42  | 54 | 1  |
| 43  | 55 | 1  |
| 44  | 72 | 1  |
```

I'm plotting `choropleth(x=df[:s], y=df[:x1])`. But I get a blank page...

**Comment by shashi** [comment]
I also tried to plot `df[:x1] .* 1000 + 1` (county no. 1 in each state) but that doesn't work either...

**Comment by randyzwitch** [comment]
Sorry, the documentation should be more specific that it is FIPS county code that has been implemented so far.

https://en.m.wikipedia.org/wiki/FIPS_county_code

State-level requires a different topojson file, which I haven't implemented yet. Is this something you need quickly or are you just exploring?

**Comment by shashi** [comment]
I needed it for one of Alan's demos in a presentation, I guess it's too late now. Will be good to have next time :)

**Comment by randyzwitch** [comment]
Here's the approximate JSON solution, just need to build the data join functionality:


```json
{
  "width": 900,
  "height": 560,
  "padding": "auto",

  "data": [
    {
      "name": "states",
      "url": "data/us-10m.json",
      "format": {"type": "topojson", "feature": "states"},
      "transform": [
        {
          "type": "geopath", "projection": "albersUsa",
          "scale": 1200, "translate": [450, 280]
        }
      ]
    }
  ],

  "scales": [
    {
      "name": "size",
      "type": "ordinal",
      "domain": {"data": "states"},
      "range": "blue"
    }
  ],

  "marks": [
    {
      "type": "path",
      "from": {"data": "states"},
      "properties": {
        "enter": {
          "path": {"field": "layout_path"},
          "fill": {"value": "blue"},
          "stroke": {"value": "white"}
        }
      }
    }
  ]
}
```

**Comment by randyzwitch** [comment]
Implemented. The state FIPS codes are used as the join values; note that it's not just values 1-50 by alphabetical order. I'll be including a table reference in the documentation.

x = [1:60]
y = rand(Float64, 60)

a = choropleth(x = x, y = y, entity = :usstates)

![usstates](https://cloud.githubusercontent.com/assets/2762787/10796996/f3e72dd0-7d76-11e5-862f-22c2f3204dcf.png)
