### ISSUE TITLE
Add more interactivity to hover!

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#70]
Next push to master will have `hover!` function, which only allows for changing opacity when hovering over graph. This is a great step to making it obvious which mark you are pointing at, but should consider other interactions/displays that could be useful on hover

- [x] Add color changing
- [ ] Add text label popup (tooltip)
- [x] ~~Allow for arbitrary HTML to be passed (unclear if possible)~~

cc: @spencerlyon2

**Comment by randyzwitch** [comment]
- Color change (instead of opacity, though both could be used I suppose)
- Pop-up value (called tooltip I think in Vega-speak)

Don't think there's too much else in terms of interactivity for this function, given there is Escher and vega-embed that can also work as backends for true interactivity.

**Comment by cstjean** [comment]
With Bokeh, I could put arbitrary HTML inside the tooltips, and we used it to display the image associated to each dot in our scatter plots. It was very useful.

**Comment by randyzwitch** [comment]
Thanks. Would you expect that functionality like adding arbitrary HTML be done during the plotting function call (i.e. just one more data element to go along with x, y, group etc.) or would you expect to be able to pass an array of HTML in the `hover!` function?

**Comment by cstjean** [comment]
I would be fine with passing it to the plotting call, but it will work either way.

**Comment by randyzwitch** [comment]
From what I can tell, it is not possible to pass arbitrary HTML through the Vega specification as a tooltip, as there are no examples of this, nor do I see anything suggestion evaluation is possible outside of the formula interface (which is for data).

Will leave as a back-burner, nice-to-have feature

**Comment by randyzwitch** [comment]
After playing with tooltip a bit, I think it needs to be its own method, rather than tacked on to `hover!`. The display of text labels inside data elements is complex, given that not all charts have X-Y coordinates (and even within X-Y coordinates, placement is a challenge

**Comment by altosaar** [comment]
@cstjean how were you able to do this in bokeh? I haven't been able to figure it out and it doesn't look like it's officially supported: https://github.com/bokeh/bokeh/issues/2833

Thanks a lot!

**Comment by cstjean** [comment]
@altosaar 
```python
hover = fig.select(dict(type=HoverTool))
hover.tooltips = html_string
```

We use it at [Recursion](http://www.recursionpharma.com/), the results are really cool.

**Comment by altosaar** [comment]
Sweet, thanks! The projects at Recursion sound awesome too.
