### ISSUE TITLE
Joint KDE

### ISSUE THREAD

**Issue by randyzwitch** [johnmyleswhite/Vega.jl#72]
Feels like all the heavy lifting for this is already done by the `KernelDensity` package. Would this just use `heatmap` that's already defined? 

Make it look something like Seaborn jointplot?
https://stanford.edu/~mwaskom/software/seaborn/tutorial/distributions.html

**Comment by randyzwitch** [comment]
Have a working example in the vega editor, need to figure out how to make it less fragile on the vega end

![screen shot 2015-11-04 at 2 45 12 pm](https://cloud.githubusercontent.com/assets/2762787/10951314/d4bb8458-830a-11e5-988e-81d512c30fda.png)

**Comment by johnmyleswhite** [comment]
Looking pretty nice, Randy.

**Comment by randyzwitch** [comment]
Thanks! Now that I've matched/passed Vincent in capabilities, now I'm aiming at Seaborn. That and @spencerlyon2 is greedy.
