### ISSUE TITLE
`Vega gives error for Julia 0.4 on Windows10 -32bit

### ISSUE THREAD

**Issue by uozden** [johnmyleswhite/Vega.jl#78]
Dear @randyzwitch, I have installed Vega and typed in the code below for piechart. It gives the following error. I am using Julia 0.4 on Windows 10 -32bit. Thank you for your help. 
````````
using Vega
fruit = ["peaches", "plums", "blueberries", "strawberries", "bananas"]
bushels = [100, 32, 180, 46, 21]
piechart(x = fruit, y = bushels)


```````````
``````````
The error
LoadError: TypeError: typeassert: expected Union{AbstractString,Array{T,N},Tuple{AbstractString,Int64}}, got Tuple{ASCIIString,Int32}
while loading In[6], in expression starting on line 6

 in piechart at C:\........\.julia\v0.4\Vega\src\derived/piechart.jl:31
`````````
````````

**Comment by randyzwitch** [comment]
Sorry about that, I had a few spare `Int64` references instead of just `Int`. If you do `Pkg.checkout("Vega")`, it should be fixed now.

**Comment by uozden** [comment]
Dear @randyzwitch, no sorry please. Having done  `Pkg.checkout("Vega")` ,it works now. I found that Vega is a great package. Thank you for your prompt help.

**Comment by randyzwitch** [comment]
Great, glad to hear it's working for you! If you have any other issues, please feel free to file them, I'd love to work out any additional rough edges that might be present.
