### ISSUE TITLE
contains method not defined

### ISSUE THREAD

**Issue by shashi** [johnmyleswhite/Vega.jl#8]
In a notebook:
```julia
using Vega

plot(x = [1, 2, 3, 4, 5],
     y = [1, 2, 3, 2, 1],
     kind = :bar)
```
results in:
```
`contains` has no method matching contains(::Array{Symbol,1}, ::Symbol)
while loading In[2], in expression starting on line 1

 in VegaAxis at /home/shashi/.julia/v0.3/Vega/src/primitives/axis.jl:69
 in VegaAxis at /home/shashi/.julia/v0.3/Vega/src/primitives/axis.jl:96
 in barplot at /home/shashi/.julia/v0.3/Vega/src/derived/barplot.jl:47
 in plot at /home/shashi/.julia/v0.3/Vega/src/derived/plot.jl:15
```

is the fix to just define the method or is there something else going on?

**Comment by johnmyleswhite** [comment]
I would imagine this is a method that got replaced with `in` since I wrote that code.

**Comment by randyzwitch** [comment]
I've been cleaning this up using v0.4 and everything works fine. I wasn't planning on messing with the Compat stuff, since I don't know how far I'm going to get before I get bored :)

**Comment by randyzwitch** [comment]
Actually, did you pull from master? Not guaranteeing that it will work, but I think that issue was fixed here https://github.com/johnmyleswhite/Vega.jl/commit/ab6ffcc85595e25255b280acaa840e627479bd66

Switching the Dict syntax was causing an implicit conversion

**Comment by shashi** [comment]
Oh! My bad! I was just using the latest release. Checking out master fixes
this yes.

**Comment by randyzwitch** [comment]
No problem. I'll probably tag a 0.0.1 release soon, so that this package will be minimally working for anyone installing via METADATA
