### ISSUE TITLE
plotline with "Date" data in axis

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#80]
Hi,

I am trying to plot a time series with Vega.jl. However, my X data represents dates and Vega.jl doesn't seem to work with Date data.

Here there is a code example: 

        using Vega
        Date(2015,11,21)
        start = Date(2015,11,21)
        days=100
        x = map(d -> start + Dates.Day(d), 1:days)
        y = 15 + randn(days) * 4
        myplot = lineplot(x=x,y=y)

In my machine, I got an empty plot. 
![wrongplot](https://cloud.githubusercontent.com/assets/5500983/11321067/47fad672-90b1-11e5-92e1-aafaf2200efa.png)

I am running Julia Version 0.4.2-pre+15 (2015-11-20 12:12 UTC) in a Ubuntu 14.04

**Comment by randyzwitch** [comment]
Thanks for pointing this out, I definitely need to detect the data types better.

If you need a quick fix, this works:

```julia
a = lineplot(x = [string(x) for x in x], y = y)
a.scales[1]._type = "ordinal"
a
```

You'll still have to mess with the axis formatting, but it plots.

I'll patch this is the next day or two, then push a new version.

**Comment by cndesantana** [comment]
Great, thanks!

**Comment by randyzwitch** [comment]
Closing in favor of meta issue
