### ISSUE TITLE
How to make the heatmap to be a continuum in the X-axis (remove gaps in the x-axis of heatmap)

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#86]
Hi,

Actually I don't know very well how to say what is my problem. I can now plot a heatmap from a dataframe. However, in the X-axis there are blank spaces between two "columns" of the heatmap. The same does not happen in the Y-axis. 

Please take a look at the following code:

        mydf = DataFrame(d0 = rep(collect(0:0.25:0.75),4), A = [rep(0.0,4);rep(0.25,4);rep(0.5,4);rep(0.75,4)], dc = rand(16))
        hm = heatmap(x = mydf[:d0], y = mydf[:A], color = mydf[:dc]);
        hm.background = "white"
        hm

that creates the following picture:

![heatmap](https://cloud.githubusercontent.com/assets/5500983/11379637/a6b87aba-92f1-11e5-8f5c-1b044afd959e.png)

I was wondering if the blank "columns" could disappear, making the heatmap to be a continuum in the X-axis as like as it is in the Y-axis. I suppose one way to do it is to define the width of the columns depending on the number of columns or something like this.

Thanks again! ;)

**Comment by randyzwitch** [comment]
This is what I meant in #84 that the result isn't going to look pretty, because the input types aren't correct. I need to figure out how to make Julia recognize the data type in Vega, so that the bar width isn't necessary (if you do `hm.marks[1].properties.enter.width = VegaValueRef(value = 268); hm` it sort of works, but it's a poor representation of the data.

**Comment by cndesantana** [comment]
Ah, ok! I though in #84 you were talking about the tick-labels in the X-axis. Now I see. 

Thanks for the workaround! It helps a lot. 

In my case, the best "VegaValueRef" seems to be 80.

        hm.marks[1].properties.enter.width = VegaValueRef(value = 80); hm

Thanks!

**Comment by randyzwitch** [comment]
Closing in favor of meta issue
