### ISSUE TITLE
ENH: center titles

### ISSUE THREAD

**Issue by spencerlyon2** [johnmyleswhite/Vega.jl#9]
We should change [this line](https://github.com/johnmyleswhite/Vega.jl/blob/575a6274abad6309cc69c59e648f01fa83f02743/src/intermediates/modifiers.jl#L31) so that instead of just setting x equal to the middle of the figure, we choose something further to the left based on the length of the title string.

**Comment by spencerlyon2** [comment]
Actually, what is the difference between those two `title!` methods?

Based on the method signatures, it looks like the first one (the one I linked to) is being shadowed by the second one...

**Comment by randyzwitch** [comment]
Ha! I never noticed the duplication. Going back through history, that's been there since John started the package. I just blindly made it 0.4 compatible ;)

The offset should be -50, but really I should just make it a keyword argument. But this graph looks good to me:

http://johnmyleswhite.github.io/Vega.jl/title.html

**Comment by spencerlyon2** [comment]
An alternative is to add another axis at the top that is not visible, but has a text label. 

I kinda like this approach because it would take care of centering the title for us and it would also allow us to change the title later. Right now we can change the title, we just add a whole separate mark so it just adds the new text without removing what was already there. If it were an axis that we could identify after creation, subsequent calls to title! could just use the existing axis and alter the text. 

Thoughts from the  experts?

**Comment by randyzwitch** [comment]
I think it's important to see what Vega 2 has done, because centering has come up on their mailing list. I'll try and look at this later tonight.

**Comment by spencerlyon2** [comment]
I had time and wanted to see if I could understand how the code here works... See #10

**Comment by randyzwitch** [comment]
Closing this in favor of the more generic meta-issue #35

**Comment by randyzwitch** [comment]
FWIW, I just fixed this @spencerlyon2, now it's true center by default, calculated by Vega. Will be in next push.

**Comment by spencerlyon2** [comment]
Awesome, good work!
