### ISSUE TITLE
ERROR: unknown package NoveltyColors required by Vega

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#92]
Hi,

I am trying to run Vega.jl and it is showing an error associated to NoveltyColors. I know NoveltyColors.jl is a new project, but I supposed it would be installed automatically if Vega.jl needs it to run. Am I right here?

By the way: I am running Julia Version 0.4.2-pre+16 (2015-11-23 23:01 UTC) in a Ubuntu 14.04 machine.

julia> Pkg.checkout("Vega")
INFO: Checking out Vega master...
INFO: Pulling Vega latest master...
ERROR: unknown package NoveltyColors required by Vega
 in error at ./error.jl:21
 in requirements at ./pkg/query.jl:11
 in resolve at ./pkg/entry.jl:404
 in resolve at pkg/entry.jl:404
 in anonymous at pkg/entry.jl:198
 in transact at pkg/git.jl:97
 in _checkout at pkg/entry.jl:190
 in checkout at pkg/entry.jl:205
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in checkout at pkg.jl:37

**Comment by randyzwitch** [comment]
It should work...meaning, Vega has it on the REQUIRES file and it's on METADATA. Maybe do Pkg.update()?

**Comment by cndesantana** [comment]
Yes, you are right. Pkg.update() followed by Pkg.checkout("Vega") solved my problem. Thanks! Sorry for thinking it was an error.
