### ISSUE TITLE
Implement node.js Vega command line tools

### ISSUE THREAD

**Issue by cndesantana** [johnmyleswhite/Vega.jl#93]
Hi,

Assume I have the following simple code that plots a time series with Vega.jl:

```
    using Vega

    function testplot(N::Int)
        x = collect(1:N);
        y = rand(N);

        myplot=lineplot(x = x, y = y)

        xlab!(myplot,title="Time")
        ylab!(myplot,title="Variable")
        title!(myplot,title="Time Series")
        myplot.background = "white"
        myplot
    end

    testplot(parse(Int,ARGS[1]))
```

Assume this code is in a file called test.jl

I ran the julia script test.jl from a linux terminal:

```
    $ julia test.jl 100
```

And I was expecting that a plot would appear in my browser with the time series. But it did not happen! The program completed its execution but no figure appeared.

However, If I call the testplot function from a Julia terminal, it works perfectly.

```
    julia> testplot(100)
```

![testfigure](https://cloud.githubusercontent.com/assets/5500983/11603961/f89e3926-9ae6-11e5-9178-6fb4a7310cea.png)

Is there any limitation to call a function from the command line? Or am I doing something wrong here?

If there is such a limitation, would it be possible to change it?

Thanks!

**Comment by randyzwitch** [comment]
Are you aware of other plotting libraries in Julia that have this functionality? I can't think of a way to do this at the moment, so I'll either need to see an example from someone else or ask on the mailing list if this is even possible.

**Comment by cndesantana** [comment]
Thanks for your response,

Vega.jl is the first Julia library I use for plotting, so I don't really know if any other library has this feature. But I hope so :)

Particularly I am not on a rush, I just found strange that running a script from the command line the results were different from running the same function in a Julia terminal. I thought it was an error of mine.

Maybe it is my R-programmer bias. :)

Charles
________________________________

**Comment by cndesantana** [comment]
Hi again,

I see your point now. That it is really difficult to create a plot in the browser calling a function from the terminal. And that other Julia libraries don't do it neither.

So, I was wondering if it would be possible to generate a figure automatically (no need to click in the link in the browser). Something like the function "draw" in "Gadfly.jl":

using Gadfly

myplot = plot(x=rand(10), y=rand(10), Geom.point, Geom.line);
draw(PNG("myplot.png", 4inch, 3inch), myplot);

Would it be possible to implement something like "draw" in Vega.jl? Should I open another issue about it?

Thanks!

Charles




________________________________
From: De Santana, Charles,
Sent: Saturday, December 05, 2015 3:04 AM
To: johnmyleswhite/Vega.jl; johnmyleswhite/Vega.jl
Subject: RE: [Vega.jl] Differences between calling a plot function in the command line and in the Julia terminal (#93)

Thanks for your response,

Vega.jl is the first Julia library I use for plotting, so I don't really know if any other library has this feature. But I hope so :)

Particularly I am not on a rush, I just found strange that running a script from the command line the results were different from running the same function in a Julia terminal. I thought it was an error of mine.

Maybe it is my R-programmer bias. :)

Charles
________________________________

**Comment by randyzwitch** [comment]
No, there is no need to open another issue. 

The only way to do this is have a dependency on node.js. I'll try to write a Julia function that depends on node.js, but it will only be a "soft dependency" (meaning the individual user will be responsible for installing node.js correctly and having it on their PATH)

**Comment by randyzwitch** [comment]
https://github.com/vega/vega/wiki/Headless-Mode
