### ISSUE TITLE
Barplot x values out of order

### ISSUE THREAD

**Issue by JobJob** [johnmyleswhite/Vega.jl#97]
using Vega
    using Distributions

    d = Normal(2,1)
    x = rand(d, 1000)
    a,b = hist(x,20)
    barplot(x = a[2:end], y=b)

Expected the x values to be in numerical order (-0.5 : 0.5 : 5.5), but they end up in an unusual order:

![barplot](https://cloud.githubusercontent.com/assets/854183/12224256/b3ff527a-b7f4-11e5-90db-e20d65cba3ae.png)

Had a quick stab at fixing it but couldn't get to the bottom of it. Cheers.

**Comment by randyzwitch** [comment]
Wow, that's pretty special. I'll take a look at this today, hopefully it's something trivial.

**Comment by JobJob** [comment]
Ha cheers.

**Comment by randyzwitch** [comment]
https://github.com/vega/vega/issues/491

**Comment by randyzwitch** [comment]
Side note: there is a histogram function that does part of you want (but currently, returning the incorrect visualization since it's based on the bar chart). I noticed `histogram` doesn't provide for number of desired bars as input, so adding that now.

**Comment by JobJob** [comment]
Nice

**Comment by randyzwitch** [comment]
Fixed, will tag a new version shortly
![download](https://cloud.githubusercontent.com/assets/2762787/12421008/f62c27be-be8d-11e5-830b-7495cb866823.png)

**Comment by JobJob** [comment]
Good form!
